#!/usr/bin/env bash
set -euo pipefail

DEFAULT_PORT=18080
REPOSITORY="qingan123/Chat2API"
REPO_URL="${CHAT2API_REPO_URL:-https://github.com/${REPOSITORY}.git}"
GIT_REF="${CHAT2API_GIT_REF:-main}"
DEPLOY_TYPE="fork"
PROJECT_NAME="Chat2API 用户 Fork版"

log() { printf '[Chat2API] %s\n' "$*"; }
die() { printf '[Chat2API] 错误：%s\n' "$*" >&2; exit 1; }
require_root() { [ "$(id -u)" -eq 0 ] || die "请使用 root 或 sudo 执行。"; }

read_tty() {
  [ -r /dev/tty ] || die "无法读取交互终端。请在 SSH 终端中运行此脚本。"
  IFS= read -r "$@" </dev/tty
}

prompt_inputs() {
  local first second
  if [ -n "${CHAT2API_PORT:-}" ]; then PORT="$CHAT2API_PORT"; else
    read_tty -p "请输入部署端口 [$DEFAULT_PORT]: " PORT
    PORT="${PORT:-$DEFAULT_PORT}"
  fi
  [[ "$PORT" =~ ^[0-9]+$ ]] && [ "$PORT" -ge 1 ] && [ "$PORT" -le 65535 ] || die "端口必须是 1-65535 的数字。"

  if [ -n "${CHAT2API_ADMIN_USERNAME:-}" ]; then ADMIN_USERNAME="$CHAT2API_ADMIN_USERNAME"; else
    read_tty -p "请输入管理员账号 [admin]: " ADMIN_USERNAME
    ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
  fi
  [[ "$ADMIN_USERNAME" =~ ^[A-Za-z0-9._-]{1,64}$ ]] || die "管理员账号仅允许字母、数字、点、下划线和短横线，最长 64 位。"

  if [ -n "${CHAT2API_ADMIN_PASSWORD:-}" ]; then
    ADMIN_PASSWORD="$CHAT2API_ADMIN_PASSWORD"
  else
    read_tty -s -p "请输入管理员密码（至少 6 位）: " first; printf '\n' >/dev/tty
    read_tty -s -p "请再次输入管理员密码: " second; printf '\n' >/dev/tty
    [ "$first" = "$second" ] || die "两次输入的管理员密码不一致。"
    ADMIN_PASSWORD="$first"
  fi
  [ "${#ADMIN_PASSWORD}" -ge 6 ] || die "管理员密码至少需要 6 位。"
  [[ "$ADMIN_PASSWORD" != *$'\n'* && "$ADMIN_PASSWORD" != *$'\r'* ]] || die "管理员密码不能包含换行符。"
}

port_is_listening() {
  ss -ltn "sport = :$1" 2>/dev/null | grep -q LISTEN
}

install_packages() {
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y ca-certificates curl git openssl python3
  if ! command -v docker >/dev/null 2>&1; then
    apt-get install -y docker.io
  fi
  systemctl enable --now docker
  docker version >/dev/null 2>&1 || die "Docker 服务不可用。"
}

clone_source() {
  log "克隆 $REPOSITORY"
  git clone --branch "$GIT_REF" --single-branch "$REPO_URL" "$SOURCE_DIR"
  SOURCE_HEAD="$(git -C "$SOURCE_DIR" rev-parse HEAD)"
  VERSION="$(git -C "$SOURCE_DIR" rev-parse --short=12 HEAD)"
}

write_runtime_config() {
  umask 077
  API_KEY="c2a_$(openssl rand -hex 32)"
  STORAGE_KEY="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
CHAT2API_HOST=0.0.0.0
CHAT2API_PORT=8080
CHAT2API_DATA_DIR=/data
CHAT2API_ENABLE_MANAGEMENT_API=true
CHAT2API_MANAGEMENT_SECRET=$ADMIN_PASSWORD
CHAT2API_ADMIN_USERNAME=$ADMIN_USERNAME
CHAT2API_ENABLE_API_KEY=true
CHAT2API_STORAGE_ENCRYPTION_KEY=$STORAGE_KEY
EOF
  printf '%s\n' "$API_KEY" > "$KEY_FILE"
  printf '%s\n' "$ADMIN_USERNAME" > "$ADMIN_USER_FILE"
  chmod 600 "$ENV_FILE" "$KEY_FILE" "$ADMIN_USER_FILE"

  CHAT2API_DATA_FILE="$DATA_DIR/data.json" CHAT2API_API_KEY="$API_KEY" CHAT2API_KEY_ID="server-$PORT" python3 - <<'PY'
import json, os, time
path=os.environ['CHAT2API_DATA_FILE']; key=os.environ['CHAT2API_API_KEY']; key_id=os.environ['CHAT2API_KEY_ID']
data={
  'providers': [], 'accounts': [], 'logs': [], 'requestLogs': [],
  'systemPrompts': [], 'sessions': [], 'statistics': {}, 'userModelOverrides': {},
  'config': {
    'proxyPort': 8080, 'proxyHost': '0.0.0.0', 'autoStartProxy': True,
    'enableApiKey': True,
    'apiKeys': [{'id': key_id, 'name': 'server-default', 'key': key, 'enabled': True,
                 'createdAt': int(time.time()*1000), 'usageCount': 0,
                 'description': 'Generated by the interactive installer'}]
  }
}
tmp=path+'.tmp'
with open(tmp,'w',encoding='utf-8') as f: json.dump(data,f,ensure_ascii=False,indent=2)
os.replace(tmp,path)
PY
  chmod 600 "$DATA_DIR/data.json"
}

build_image() {
  IMAGE_TAG="chat2api-qingan:${PORT}-${VERSION}"
  log "构建原生 WebUI 服务镜像 $IMAGE_TAG"
  docker build -t "$IMAGE_TAG" "$SOURCE_DIR"
}

write_meta() {
  cat > "$META_FILE" <<EOF
TYPE=$DEPLOY_TYPE
PROJECT_NAME=$PROJECT_NAME
PORT=$PORT
VERSION=$VERSION
SOURCE_HEAD=$SOURCE_HEAD
APP_DIR=$APP_DIR
SOURCE_DIR=$SOURCE_DIR
DATA_DIR=$DATA_DIR
ENV_FILE=$ENV_FILE
KEY_FILE=$KEY_FILE
ADMIN_USER_FILE=$ADMIN_USER_FILE
CONTAINER_NAME=$CONTAINER_NAME
IMAGE_TAG=$IMAGE_TAG
REPOSITORY=$REPOSITORY
GIT_REF=$GIT_REF
EOF
  chmod 600 "$META_FILE"
}

start_container() {
  docker run -d \
    --name "$CONTAINER_NAME" \
    --restart unless-stopped \
    --env-file "$ENV_FILE" \
    -p "${PORT}:8080" \
    -v "$DATA_DIR:/data" \
    "$IMAGE_TAG" >/dev/null
}

verify_instance() {
  local i health code key
  for i in $(seq 1 120); do
    if health="$(curl -fsS --max-time 3 "http://127.0.0.1:$PORT/health" 2>/dev/null)" && \
       python3 -c 'import json,sys; assert json.load(sys.stdin).get("status")=="running"' <<<"$health" 2>/dev/null; then break; fi
    if [ "$i" -eq 120 ]; then docker logs --tail 150 "$CONTAINER_NAME" || true; die "健康检查超时。"; fi
    sleep 2
  done
  code="$(curl -sS -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/admin/")"
  [ "$code" = 200 ] || die "管理页面应返回 200，实际为 $code。"
  code="$(curl -sS -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $ADMIN_PASSWORD" -H 'X-Admin-Username: invalid-user' "http://127.0.0.1:$PORT/v0/management/health")"
  [ "$code" = 401 ] || die "错误管理员账号应返回 401，实际为 $code。"
  code="$(curl -sS -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $ADMIN_PASSWORD" -H "X-Admin-Username: $ADMIN_USERNAME" "http://127.0.0.1:$PORT/v0/management/health")"
  [ "$code" = 200 ] || die "正确管理员账号密码应返回 200，实际为 $code。"
  code="$(curl -sS -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/v1/models")"
  [ "$code" = 401 ] || die "未认证模型接口应返回 401，实际为 $code。"
  key="$(<"$KEY_FILE")"
  code="$(curl -sS -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $key" "http://127.0.0.1:$PORT/v1/models")"
  [ "$code" = 200 ] || die "API Key 验证失败，模型接口返回 $code。"
  docker restart "$CONTAINER_NAME" >/dev/null
  for i in $(seq 1 60); do curl -fsS --max-time 3 "http://127.0.0.1:$PORT/health" >/dev/null 2>&1 && return; sleep 2; done
  die "容器重启后健康检查失败。"
}

print_result() {
  local public_host="${PUBLIC_HOST:-}"
  [ -n "$public_host" ] || public_host="$(curl -4fsS --max-time 8 https://api.ipify.org 2>/dev/null || true)"
  printf '\n部署完成：%s %s\n' "$PROJECT_NAME" "$VERSION"
  printf '安装目录：%s\n' "$APP_DIR"
  printf '管理员账号文件：%s\n' "$ADMIN_USER_FILE"
  printf '管理员密码：使用安装时输入的密码（不会写入输出）\n'
  printf 'API Key 文件：%s（仅 root 可读）\n' "$KEY_FILE"
  printf '本机管理后台：http://127.0.0.1:%s/admin/\n' "$PORT"
  printf '本机 OpenAI Base URL：http://127.0.0.1:%s/v1\n' "$PORT"
  if [ -n "$public_host" ]; then
    printf '公网管理后台：http://%s:%s/admin/\n' "$public_host" "$PORT"
    printf '公网 OpenAI Base URL：http://%s:%s/v1\n' "$public_host" "$PORT"
  else
    printf '公网地址探测失败；可设置 PUBLIC_HOST 后使用实际公网地址。\n'
  fi
  printf '容器状态：docker ps --filter name=^/%s$\n' "$CONTAINER_NAME"
  printf '实时日志：docker logs -f %s\n' "$CONTAINER_NAME"
  printf '注意：请另行确认云安全组、UFW、NAT 或反向代理已放行端口 %s。\n' "$PORT"
}

main() {
  require_root
  prompt_inputs
  APP_DIR="${APP_DIR_BASE:-/opt/chat2api-$PORT}"
  SOURCE_DIR="$APP_DIR/source"
  DATA_DIR="$APP_DIR/data"
  ENV_FILE="$APP_DIR/runtime.env"
  KEY_FILE="$APP_DIR/api-key.txt"
  ADMIN_USER_FILE="$APP_DIR/admin-username.txt"
  META_FILE="$APP_DIR/.chat2api-deploy"
  CONTAINER_NAME="chat2api-$PORT"
  port_is_listening "$PORT" && die "端口 $PORT 已被占用。"
  [ ! -e "$APP_DIR" ] || die "安装目录已存在：$APP_DIR；请使用更新脚本。"
  install_packages
  install -d -m 755 "$APP_DIR"
  install -d -m 700 "$DATA_DIR"
  clone_source
  write_runtime_config
  build_image
  write_meta
  start_container
  verify_instance
  print_result
}
main "$@"
